# Generated by Django 4.0.1 on 2022-01-07 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationUnit',
            fields=[
                ('SerialNumber', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Serial Number')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communication Unit',
                'verbose_name_plural': 'Communication Units',
            },
        ),
        migrations.CreateModel(
            name='CommunicationUnitCCIDetails',
            fields=[
                ('SerialNumber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CommunicationUnits.communicationunit')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Device Name')),
                ('machineSerialNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Machine Serial Number')),
                ('machineNameSeries', models.CharField(blank=True, max_length=100, null=True, verbose_name='Machine Name Series')),
                ('machineProductionYear', models.CharField(blank=True, max_length=100, null=True, verbose_name='Machine Production Year')),
                ('scrapped', models.BooleanField()),
            ],
            options={
                'verbose_name': 'myCCI Info',
                'verbose_name_plural': 'myCCI Info',
            },
        ),
    ]
