# Generated by Django 4.0.1 on 2022-01-08 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencedetails',
            name='expired_on',
            field=models.DateTimeField(default=datetime.datetime(2032, 1, 6, 21, 20, 4, 592992)),
        ),
    ]
