# Generated by Django 4.0.1 on 2022-01-07 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licences', '0002_alter_licencedetails_expired_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencedetails',
            name='expired_on',
            field=models.DateTimeField(default=datetime.datetime(2032, 1, 5, 12, 1, 46, 175353)),
        ),
    ]
